language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anil-k-n/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anil-k-n/docker-react npm run test